name: Mirror

on:
  workflow_dispatch:
  schedule:
  - cron: "5 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch
        run: git fetch https://github.com/ros-industrial/industrial_ci.git -n master:mirror-master legacy:mirror-legacy
      - name: Push
        run: git push origin mirror-master mirror-legacy
